# Header
menu:
  首页: /
  文章: /archives
  加入我们: /about

# Content
excerpt_link: 阅读全文

# Toc
toc: false

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /favicon.ico
webclip: /images/webclip
brand:   /favicon.ico

# Jumbotron video & Hero image
## Jumbotron video
video: 
  overlay: true
  path: /images/
## Hero image
hero: 
  image: /images/banner.png
## keen-slider
keen_slider: 
  enable: false

# Slogan
slogan: 
  primary: 
  secondary: 
  archives: 
  pages: 
  posts: 

